export interface Product {
    _id: string,
    name: string,
    brandName:string,
    itemNo:string,
    supplierName: string,
    weight: string,
    weightq: string,
    quantity:string,
    regular:String,
    groupOrder: String,
  quickQuote: String ,
  uniform:String ,
  printted:String ,
  embroidery: String,
  description:string,

  price: String,
  sizes: String ,
  sizem: String ,
  sizel: String ,
  sizexl: String,
  information1:String,
  information2: String,

  ColorID: String,
  additionalPrice: String,
  colorName: String,
  colorCode: String,
  frontImage: String,
  frontThumb:String,
  backImage: String,
  backThumb:String,
  rightImage: String,
  rightThumb:String,
  leftImage: String,
  leftThumb:String,

  men:String,
  women:String,
  m_ts_shortSleeve: String,
  m_ts_longSleeve: String,
  m_ts_performance: String,
  m_sh_shortSleeve: String,
  m_sh_longSleeve: String,
  m_sh_performance: String,
  m_po_shortSleeve: String,  
  m_po_longSleeve: String,
    
  w_ts_shortSleeve: String,
  w_ts_longSleeve: String,
  w_ts_performance: String,
  w_sh_shortSleeve: String,
  w_sh_longSleeve: String,
  w_po_shortSleeve: String,  
  w_po_longSleeve: String,

  status: String
}